server:
  port: 8080
  servlet:
    context-path: /kafka


spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092 #Kafka的消息中间件服务器
          zk-nodes: localhost:2181 #Zookeeper的节点，如果集群，后面加,号分隔
          auto-create-topics: true  #如果设置为false,就不会自动创建Topic 有可能你Topic还没创建就直接调用了
      bindings:
        output:      #这里用KafkaSource.class中定义的
          destination: kafka-topic    #消息发往的目的地 topic
          content-type: application/json    #消息发送的格式，接收端不用指定格式，但是发送端要，一般都是json
        input: # 这里用KafkaSink.class 中定义的
          destination: kafka-topic # topic
          content-type: application/json